repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        exclude: migrations,settings.py,.venv/
        args: [--max-line-length=120, --ignore=E402 E501]
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        exclude: migrations,settings.py,.venv/
        args: [--line-length=120, --extend-exclude=E402 E501]
        language: system
        types: [python]