repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8
        exclude: migrations,settings.py,.venv/
        args: [--ignore=E402]
        language: system
        types: [python]
      - id: black
        name: black
        entry: black
        exclude: migrations,settings.py,.venv/
        args: [--extend-exclude=E402]
        language: system
        types: [python]