# Generated by Django 3.2.23 on 2024-01-20 14:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutor",
            name="avatar_image",
            field=cloudinary.models.CloudinaryField(
                default="https://res.cloudinary.com/difmdvoze/image/upload/v1705534784/static/images/placeholder.jpg",
                max_length=255,
                verbose_name="image",
            ),
        ),
    ]
