# Generated by Django 3.2.23 on 2024-01-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutor", "0003_alter_tutor_avatar_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instrument",
            name="color",
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name="musicstyle",
            name="color",
            field=models.CharField(max_length=7),
        ),
    ]
