# Generated by Django 4.2.9 on 2024-01-14 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("booking_time", models.CharField(max_length=5)),
                (
                    "booking_status",
                    models.IntegerField(
                        choices=[
                            (0, "Awaiting Confirmation"),
                            (1, "Confirm Booking"),
                            (2, "Booking Declined"),
                        ],
                        default=0,
                    ),
                ),
                ("message", models.CharField(max_length=200, unique=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_tutor",
                        to="tutor.tutor",
                    ),
                ),
            ],
        ),
    ]
